# Step 1:
       Import pandas

In [1]:
import pandas as pd

# Step 2:
       read(import ) csv file.

In [3]:
df=pd.read_csv("ml_dataset.csv.csv")
df

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
0,1,2022-04-17,21.0,Male,Islamabad,Home Office,Sports,73359.0,0,56,...,1407.71,56308.38,13.6,42,63.5,9.0,NaN,1,0,0
1,2,2022-10-19,28.0,Male,Karachi,Home Office,Grocery,117472.0,9,306,...,2288.52,45770.35,3.7,73,43.4,2.0,630.0,0,2,1
2,3,2025-08-16,48.0,Other,Faisalabad,Small Business,Sports,111405.0,25,268,...,41065.40,82130.80,0.5,85,38.3,9.0,729.0,1,4,1
3,4,2024-07-24,50.0,Female,Multan,Consumer,Furniture,137462.0,30,43,...,4955.74,113982.07,35.4,75,8.8,6.0,831.0,1,0,0
4,5,2025-07-14,58.0,Other,Peshawar,Small Business,Furniture,31262.0,37,208,...,413.81,16138.63,38.6,19,89.3,5.0,641.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10095,4700,2023-06-24,30.0,Male,Hyderabad,Corporate,Grocery,100597.0,4,41,...,763.36,25954.18,8.1,36,49.9,2.0,605.0,0,1,1
10096,3058,2024-05-03,20.0,Male,Multan,Home Office,Grocery,78465.0,0,200,...,8181.67,65453.34,16.0,6,72.1,2.0,590.0,0,0,1
10097,1186,2022-01-25,42.0,Male,Multan,Consumer,Books,129940.0,22,153,...,998.79,28965.01,35.7,35,12.2,10.0,830.0,0,1,0
10098,3208,2023-03-04,47.0,Female,NaN,Small Business,Electronics,135183.0,24,154,...,5676.68,NaN,28.5,60,47.1,1.0,716.0,1,0,1
10099,9463,2024-08-08,25.0,Female,Multan,Consumer,Clothing,103425.0,2,40,...,4067.18,65074.84,15.6,35,52.6,9.0,642.0,0,5,1

# step 3:head().
      => view the first through head() function.
      => when you want specific rows insert number in paranthesis.

In [4]:
df.head()

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
0,1,2022-04-17,21.0,Male,Islamabad,Home Office,Sports,73359.0,0,56,...,1407.71,56308.38,13.6,42,63.5,9.0,NaN,1,0,0
1,2,2022-10-19,28.0,Male,Karachi,Home Office,Grocery,117472.0,9,306,...,2288.52,45770.35,3.7,73,43.4,2.0,630.0,0,2,1
2,3,2025-08-16,48.0,Other,Faisalabad,Small Business,Sports,111405.0,25,268,...,41065.40,82130.80,0.5,85,38.3,9.0,729.0,1,4,1
3,4,2024-07-24,50.0,Female,Multan,Consumer,Furniture,137462.0,30,43,...,4955.74,113982.07,35.4,75,8.8,6.0,831.0,1,0,0
4,5,2025-07-14,58.0,Other,Peshawar,Small Business,Furniture,31262.0,37,208,...,413.81,16138.63,38.6,19,89.3,5.0,641.0,1,0,0

# step 4 : tail().
            => tail() is function used to see the last rows.

In [5]:
df.tail()

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
10095,4700,2023-06-24,30.0,Male,Hyderabad,Corporate,Grocery,100597.0,4,41,...,763.36,25954.18,8.1,36,49.9,2.0,605.0,0,1,1
10096,3058,2024-05-03,20.0,Male,Multan,Home Office,Grocery,78465.0,0,200,...,8181.67,65453.34,16.0,6,72.1,2.0,590.0,0,0,1
10097,1186,2022-01-25,42.0,Male,Multan,Consumer,Books,129940.0,22,153,...,998.79,28965.01,35.7,35,12.2,10.0,830.0,0,1,0
10098,3208,2023-03-04,47.0,Female,NaN,Small Business,Electronics,135183.0,24,154,...,5676.68,NaN,28.5,60,47.1,1.0,716.0,1,0,1
10099,9463,2024-08-08,25.0,Female,Multan,Consumer,Clothing,103425.0,2,40,...,4067.18,65074.84,15.6,35,52.6,9.0,642.0,0,5,1

# Step 5: shape:
           => used to know about the  number of rows and columns.

In [6]:
df.shape

(10100, 21)

# Step 6: columns:
           => to know columns

In [7]:
df.columns

Index(['CustomerID', 'JoinDate', 'Age', 'Gender', 'City', 'Segment',
       'ProductCategory', 'Income', 'YearsExperience', 'WebsiteVisits',
       'Purchases', 'AvgOrderValue', 'AnnualSpending', 'DiscountPercent',
       'EmailOpens', 'TimeOnSiteMin', 'SatisfactionScore', 'CreditScore',
       'HasSubscription', 'ReturnedItems', 'Target_Churn'],
      dtype='str')

# Step 7: info()

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         10100 non-null  int64
 1   JoinDate           10100 non-null  str
 2   Age                9898 non-null   float64
 3   Gender             10100 non-null  str
 4   City               9898 non-null   str
 5   Segment            10100 non-null  str
 6   ProductCategory    10100 non-null  str
 7   Income             9898 non-null   float64
 8   YearsExperience    10100 non-null  int64
 9   WebsiteVisits      10100 non-null  int64
 10  Purchases          10100 non-null  int64
 11  AvgOrderValue      10100 non-null  float64
 12  AnnualSpending     9898 non-null   float64
 13  DiscountPercent    10100 non-null  float64
 14  EmailOpens         10100 non-null  int64
 15  TimeOnSiteMin      10100 non-null  float64
 16  SatisfactionScore  9898 non-null   float64
 17  CreditScore        9898 non-null   float64
 18  HasSubscription    10100 non-null  int64
 19  ReturnedItems      10100 non-null  int64
 20  Target_Churn       10100 non-null  int64
dtypes: float64(8), int64(8), str(5)
memory usage: 1.6 MB

# Step 8: describe().
           => describe() function is used for statistical information.

In [9]:
df.describe()

,CustomerID,Age,Income,YearsExperience,WebsiteVisits,Purchases,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
count,10100.000000,9898.000000,9898.000000,10100.000000,10100.000000,10100.000000,10100.000000,9.898000e+03,10100.000000,10100.000000,10100.000000,9898.000000,9898.000000,10100.000000,10100.000000,10100.000000
mean,4999.962277,44.013437,80715.685088,22.265743,175.994752,19.806634,5256.314352,4.121837e+04,19.947446,50.235842,45.061584,5.500505,676.479188,0.503069,1.774158,0.524356
std,2886.828406,15.266906,34396.999950,15.098602,100.683839,11.570778,12036.068439,3.931872e+04,11.622414,29.311785,25.642800,2.879839,92.857771,0.500015,1.653098,0.499431
min,1.000000,18.000000,15000.000000,0.000000,1.000000,0.000000,33.670000,1.304060e+03,0.000000,0.000000,1.000000,1.000000,322.000000,0.000000,0.000000,0.000000
25%,2498.750000,31.000000,56195.250000,9.000000,88.000000,11.000000,901.280000,1.786140e+04,9.700000,25.000000,23.075000,3.000000,611.000000,0.000000,0.000000,0.000000
50%,4998.500000,44.000000,80902.000000,22.000000,177.000000,20.000000,1907.850000,3.416386e+04,19.900000,50.000000,44.700000,6.000000,677.000000,1.000000,2.000000,1.000000
75%,7501.250000,57.000000,104430.000000,35.000000,262.250000,28.000000,3870.367500,5.632351e+04,30.100000,76.000000,67.300000,8.000000,743.000000,1.000000,3.000000,1.000000
max,10000.000000,70.000000,209132.000000,52.000000,350.000000,73.000000,133277.650000,1.137308e+06,40.000000,100.000000,90.000000,10.000000,850.000000,1.000000,9.000000,1.000000

# Step 9: isna().
          => isna() function is used for checking missing value.

In [11]:
df.isna().sum()

CustomerID             0
JoinDate               0
Age                  202
Gender                 0
City                 202
Segment                0
ProductCategory        0
Income               202
YearsExperience        0
WebsiteVisits          0
Purchases              0
AvgOrderValue          0
AnnualSpending       202
DiscountPercent        0
EmailOpens             0
TimeOnSiteMin          0
SatisfactionScore    202
CreditScore          202
HasSubscription        0
ReturnedItems          0
Target_Churn           0
dtype: int64

# Step 10: fillna().
            => fillna() is used for filling missing value.

In [14]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['City']=df['City'].fillna(df['City'].mode()[0])
df['Income']=df['Income'].fillna(df['Income'].median())
df['AnnualSpending']=df['AnnualSpending'].fillna(df['AnnualSpending'].median())
df['SatisfactionScore']=df['SatisfactionScore'].fillna(df['SatisfactionScore'].median())
df['CreditScore']=df['CreditScore'].fillna(df['CreditScore'].median())

In [15]:
df

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
0,1,2022-04-17,21.0,Male,Islamabad,Home Office,Sports,73359.0,0,56,...,1407.71,56308.38,13.6,42,63.5,9.0,677.0,1,0,0
1,2,2022-10-19,28.0,Male,Karachi,Home Office,Grocery,117472.0,9,306,...,2288.52,45770.35,3.7,73,43.4,2.0,630.0,0,2,1
2,3,2025-08-16,48.0,Other,Faisalabad,Small Business,Sports,111405.0,25,268,...,41065.40,82130.80,0.5,85,38.3,9.0,729.0,1,4,1
3,4,2024-07-24,50.0,Female,Multan,Consumer,Furniture,137462.0,30,43,...,4955.74,113982.07,35.4,75,8.8,6.0,831.0,1,0,0
4,5,2025-07-14,58.0,Other,Peshawar,Small Business,Furniture,31262.0,37,208,...,413.81,16138.63,38.6,19,89.3,5.0,641.0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10095,4700,2023-06-24,30.0,Male,Hyderabad,Corporate,Grocery,100597.0,4,41,...,763.36,25954.18,8.1,36,49.9,2.0,605.0,0,1,1
10096,3058,2024-05-03,20.0,Male,Multan,Home Office,Grocery,78465.0,0,200,...,8181.67,65453.34,16.0,6,72.1,2.0,590.0,0,0,1
10097,1186,2022-01-25,42.0,Male,Multan,Consumer,Books,129940.0,22,153,...,998.79,28965.01,35.7,35,12.2,10.0,830.0,0,1,0
10098,3208,2023-03-04,47.0,Female,Multan,Small Business,Electronics,135183.0,24,154,...,5676.68,34163.86,28.5,60,47.1,1.0,716.0,1,0,1
10099,9463,2024-08-08,25.0,Female,Multan,Consumer,Clothing,103425.0,2,40,...,4067.18,65074.84,15.6,35,52.6,9.0,642.0,0,5,1

In [16]:
df.isna().sum()

CustomerID           0
JoinDate             0
Age                  0
Gender               0
City                 0
Segment              0
ProductCategory      0
Income               0
YearsExperience      0
WebsiteVisits        0
Purchases            0
AvgOrderValue        0
AnnualSpending       0
DiscountPercent      0
EmailOpens           0
TimeOnSiteMin        0
SatisfactionScore    0
CreditScore          0
HasSubscription      0
ReturnedItems        0
Target_Churn         0
dtype: int64

# Step 10: duplicated().
             => used for checking of duplicated rows

In [17]:
df.duplicated().sum()

np.int64(76)

# Step 11: 
       => droping of duplicated rows and columns

In [19]:
df=df.drop_duplicates()

In [20]:
df.duplicated().sum()

np.int64(0)

# Step 12: dtypes.
               => to know about data types

In [21]:
df.dtypes

CustomerID             int64
JoinDate                 str
Age                  float64
Gender                   str
City                     str
Segment                  str
ProductCategory          str
Income               float64
YearsExperience        int64
WebsiteVisits          int64
Purchases              int64
AvgOrderValue        float64
AnnualSpending       float64
DiscountPercent      float64
EmailOpens             int64
TimeOnSiteMin        float64
SatisfactionScore    float64
CreditScore          float64
HasSubscription        int64
ReturnedItems          int64
Target_Churn           int64
dtype: object

# Step 13:Selecting One Column.

In [22]:
df['Age']

0        21.0
1        28.0
2        48.0
3        50.0
4        58.0
         ...
10082    26.0
10085    55.0
10091    19.0
10093    19.0
10098    47.0
Name: Age, Length: 10024, dtype: float64

# Step 14: Selecting more than one Columns

In [25]:
df[["Age","Income"]]

        Age    Income
0      21.0   73359.0
1      28.0  117472.0
2      48.0  111405.0
3      50.0  137462.0
4      58.0   31262.0
...     ...       ...
10082  26.0   80902.0
10085  55.0  148056.0
10091  19.0   80313.0
10093  19.0  147744.0
10098  47.0  135183.0

[10024 rows x 2 columns]

# Step 15:Filter Rows.

In [26]:
df[df["Income"] > 100000]

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
1,2,2022-10-19,28.0,Male,Karachi,Home Office,Grocery,117472.0,9,306,...,2288.52,45770.35,3.7,73,43.4,2.0,630.0,0,2,1
2,3,2025-08-16,48.0,Other,Faisalabad,Small Business,Sports,111405.0,25,268,...,41065.40,82130.80,0.5,85,38.3,9.0,729.0,1,4,1
3,4,2024-07-24,50.0,Female,Multan,Consumer,Furniture,137462.0,30,43,...,4955.74,113982.07,35.4,75,8.8,6.0,831.0,1,0,0
7,8,2022-10-27,44.0,Other,Quetta,Small Business,Clothing,144983.0,24,191,...,3141.55,91104.98,21.5,16,48.6,1.0,815.0,1,0,1
10,11,2025-01-06,50.0,Male,Islamabad,Small Business,Grocery,100296.0,29,9,...,1043.14,23992.20,13.6,93,36.5,6.0,756.0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10067,5195,2022-07-03,68.0,Other,Faisalabad,Small Business,Grocery,142455.0,45,253,...,1209.23,25393.86,6.9,61,32.3,10.0,677.0,0,3,0
10072,5288,2025-12-09,49.0,Male,Karachi,Corporate,Electronics,125841.0,29,135,...,527.22,22143.10,21.6,17,34.5,10.0,767.0,1,1,0
10085,2117,2025-03-12,55.0,Male,Multan,Consumer,Clothing,148056.0,37,96,...,4381.40,122679.31,13.3,31,70.8,4.0,816.0,0,0,1
10093,626,2024-12-04,19.0,Male,Peshawar,Home Office,Clothing,147744.0,0,269,...,3097.87,58859.60,33.7,94,22.6,6.0,753.0,1,0,1
10098,3208,2023-03-04,47.0,Female,Multan,Small Business,Electronics,135183.0,24,154,...,5676.68,34163.86,28.5,60,47.1,1.0,716.0,1,0,1

# Step 16:Multiple conditions.

In [27]:
df[(df["Age"] > 30) & (df["Income"] > 100000)]

,CustomerID,JoinDate,Age,Gender,City,Segment,ProductCategory,Income,YearsExperience,WebsiteVisits,...,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
2,3,2025-08-16,48.0,Other,Faisalabad,Small Business,Sports,111405.0,25,268,...,41065.40,82130.80,0.5,85,38.3,9.0,729.0,1,4,1
3,4,2024-07-24,50.0,Female,Multan,Consumer,Furniture,137462.0,30,43,...,4955.74,113982.07,35.4,75,8.8,6.0,831.0,1,0,0
7,8,2022-10-27,44.0,Other,Quetta,Small Business,Clothing,144983.0,24,191,...,3141.55,91104.98,21.5,16,48.6,1.0,815.0,1,0,1
10,11,2025-01-06,50.0,Male,Islamabad,Small Business,Grocery,100296.0,29,9,...,1043.14,23992.20,13.6,93,36.5,6.0,756.0,0,1,1
15,16,2022-01-29,52.0,Female,Faisalabad,Corporate,Books,124572.0,31,307,...,2584.64,98216.30,28.2,8,78.6,10.0,850.0,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10066,6392,2022-06-20,53.0,Male,Multan,Small Business,Books,111825.0,30,221,...,444.73,12452.54,17.6,77,41.6,7.0,677.0,1,0,0
10067,5195,2022-07-03,68.0,Other,Faisalabad,Small Business,Grocery,142455.0,45,253,...,1209.23,25393.86,6.9,61,32.3,10.0,677.0,0,3,0
10072,5288,2025-12-09,49.0,Male,Karachi,Corporate,Electronics,125841.0,29,135,...,527.22,22143.10,21.6,17,34.5,10.0,767.0,1,1,0
10085,2117,2025-03-12,55.0,Male,Multan,Consumer,Clothing,148056.0,37,96,...,4381.40,122679.31,13.3,31,70.8,4.0,816.0,0,0,1
10098,3208,2023-03-04,47.0,Female,Multan,Small Business,Electronics,135183.0,24,154,...,5676.68,34163.86,28.5,60,47.1,1.0,716.0,1,0,1

# Step 17: Count Categories.

In [28]:
df["City"].value_counts()

City
Multan        1472
Lahore        1265
Peshawar      1233
Islamabad     1230
Quetta        1220
Karachi       1205
Faisalabad    1204
Hyderabad     1195
Name: count, dtype: int64

# Step 18: Group Data

In [30]:
df.groupby("City")["AnnualSpending"].mean()

City
Faisalabad    42254.587957
Hyderabad     40462.639431
Islamabad     38995.897382
Karachi       41072.702697
Lahore        41688.040292
Multan        42860.696250
Peshawar      40523.180568
Quetta        40627.902164
Name: AnnualSpending, dtype: float64

# Step 19: Correlation.

In [31]:
df.corr(numeric_only=True)

,CustomerID,Age,Income,YearsExperience,WebsiteVisits,Purchases,AvgOrderValue,AnnualSpending,DiscountPercent,EmailOpens,TimeOnSiteMin,SatisfactionScore,CreditScore,HasSubscription,ReturnedItems,Target_Churn
CustomerID,1.000000,-0.001342,-0.008748,-0.002677,0.010428,-0.003472,0.000152,-0.000050,-0.013227,0.014836,-0.007263,0.015022,-0.006840,0.000370,0.023195,0.010397
Age,-0.001342,1.000000,-0.020805,0.976455,-0.011702,-0.006722,-0.003637,-0.014783,0.003058,-0.006877,-0.003657,0.005177,0.438947,-0.019703,-0.015652,-0.016956
Income,-0.008748,-0.020805,1.000000,-0.022280,-0.005443,0.022619,0.171211,0.438041,-0.007087,-0.007103,0.007136,0.000153,0.697761,0.007127,-0.022039,-0.013152
YearsExperience,-0.002677,0.976455,-0.022280,1.000000,-0.011975,-0.009373,-0.005277,-0.016032,0.002320,-0.007024,-0.001589,0.001480,0.448043,-0.019448,-0.012669,-0.013369
WebsiteVisits,0.010428,-0.011702,-0.005443,-0.011975,1.000000,-0.005681,-0.003662,0.001736,0.006346,-0.017534,-0.001168,-0.010615,-0.006305,-0.000122,0.000431,-0.087751
Purchases,-0.003472,-0.006722,0.022619,-0.009373,-0.005681,1.000000,-0.479056,-0.001050,0.013485,-0.011359,-0.000494,-0.014756,0.014065,-0.002259,0.003911,0.013503
AvgOrderValue,0.000152,-0.003637,0.171211,-0.005277,-0.003662,-0.479056,1.000000,0.210312,0.000642,0.001366,-0.005011,0.007282,0.116603,0.001428,-0.004961,-0.006729
AnnualSpending,-0.000050,-0.014783,0.438041,-0.016032,0.001736,-0.001050,0.210312,1.000000,-0.000842,-0.013588,0.007390,0.011978,0.303892,0.013086,-0.001863,-0.008530
DiscountPercent,-0.013227,0.003058,-0.007087,0.002320,0.006346,0.013485,0.000642,-0.000842,1.000000,-0.006787,-0.005823,0.001859,0.002337,-0.013006,0.014744,0.000590
EmailOpens,0.014836,-0.006877,-0.007103,-0.007024,-0.017534,-0.011359,0.001366,-0.013588,-0.006787,1.000000,-0.021331,0.013063,-0.011968,-0.005268,0.002589,0.002446
TimeOnSiteMin,-0.007263,-0.003657,0.007136,-0.001589,-0.001168,-0.000494,-0.005011,0.007390,-0.005823,-0.021331,1.000000,-0.007986,0.001366,0.000186,0.000223,0.012901
SatisfactionScore,0.015022,0.005177,0.000153,0.001480,-0.010615,-0.014756,0.007282,0.011978,0.001859,0.013063,-0.007986,1.000000,-0.000994,0.008508,-0.004326,-0.654302
CreditScore,-0.006840,0.438947,0.697761,0.448043,-0.006305,0.014065,0.116603,0.303892,0.002337,-0.011968,0.001366,-0.000994,1.000000,-0.002595,-0.021077,-0.019085
HasSubscription,0.000370,-0.019703,0.007127,-0.019448,-0.000122,-0.002259,0.001428,0.013086,-0.013006,-0.005268,0.000186,0.008508,-0.002595,1.000000,0.023101,-0.000697
ReturnedItems,0.023195,-0.015652,-0.022039,-0.012669,0.000431,0.003911,-0.004961,-0.001863,0.014744,0.002589,0.000223,-0.004326,-0.021077,0.023101,1.000000,0.308921
Target_Churn,0.010397,-0.016956,-0.013152,-0.013369,-0.087751,0.013503,-0.006729,-0.008530,0.000590,0.002446,0.012901,-0.654302,-0.019085,-0.000697,0.308921,1.000000

# Step 20: 
        => Saving clean dataset

In [32]:
df.to_csv("Cleand_ml_dataset", index=False)